stages:
  - test
  - deploy

variables:
  DB_NAME: "tracker"
  DB_USER: "user"
  DB_PASS: "$SECURE_DB_PASSWORD"
  LOG_LEVEL: "INFO"
  DB_PORT: "5432"
  BOT_TOKEN: "$TELEGRAM_BOT_TOKEN"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apk add --no-cache docker-compose

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false", "--host", "tcp://0.0.0.0:2375"]

test:
  stage: test
  image: docker/compose:alpine-1.29.2
  script:
    - echo ${DB_USER}
    - docker-compose build
    - docker-compose up -d
    # - docker-compose exec -T app pytest
    - docker-compose down
  tags:
    - docker

deploy:
  stage: deploy
  image: docker:stable
  script:
    - docker compose up -d
  tags:
    - docker
  when: manual