services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - app-network

  app:
    build: 
      context: .
      target: test
    entrypoint: ["pytest", "tests"]
    environment:
      LOG_LEVEL: ${LOG_LEVEL}

      TEST_DB_NAME: ${TEST_DB_NAME}
      TEST_DB_USER: ${TEST_DB_USER}
      TEST_DB_PASS: ${TEST_DB_PASS}
      TEST_DB_HOST: db
      TEST_DB_PORT: 5432
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge