services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped 

  app:
    build: 
      context: .
      target: prod
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
      BOT_TOKEN: ${BOT_TOKEN}
    command: sh -c "alembic upgrade head &&
             python -m tracker.main"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped 

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: